# Generated by Django 4.2.27 on 2026-01-17 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='custom_months',
            field=models.IntegerField(blank=True, help_text='Number of months for custom period distribution', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='input_mode',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Input'), ('YEARLY', 'Yearly Input'), ('CUSTOM', 'Custom Period')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='yearly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for yearly/custom input mode', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(default='CHF', max_length=3),
        ),
    ]
