# Generated by Django 4.2.27 on 2026-01-18 23:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_budgetcategory_custom_months_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tax name (e.g., Einkommenssteuer, AHV)",
                        max_length=200,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax percentage (e.g., 10.5 for 10.5%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_entries",
                        to="core.budget",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tax Entries",
                "ordering": ["budget", "order", "name"],
                "unique_together": {("budget", "name")},
            },
        ),
    ]
