# Generated by Django 4.2.27 on 2026-01-18 23:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_taxentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryReduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Reduction name (e.g., AHV, Krankenkasse)",
                        max_length=200,
                    ),
                ),
                (
                    "reduction_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed Amount"),
                        ],
                        default="PERCENTAGE",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or fixed amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_reductions",
                        to="core.budget",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Salary Reductions",
                "ordering": ["budget", "order", "name"],
                "unique_together": {("budget", "name")},
            },
        ),
    ]
