# Generated by Django 4.2.27 on 2026-01-19 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_salaryreduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetcategory",
            name="custom_start_month",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="Starting month (1-12) for custom period distribution",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
    ]
