# Generated by Django 5.2.8 on 2026-01-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_monthlyactualbalance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"ordering": ["name"]},
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="budget",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name="budget",
            name="year",
        ),
    ]
